 spark-submit druid_tpd_overall.py "Andaman and Nicobar Islands"
 spark-submit druid_tpd_overall.py "APEKX"
 spark-submit druid_tpd_overall.py "Arunachal Pradesh"
 spark-submit druid_tpd_overall.py "Bihar"
 spark-submit druid_tpd_overall.py "Delhi"
 spark-submit druid_tpd_overall.py "Gujarat"
 spark-submit druid_tpd_overall.py "Haryana"
 spark-submit druid_tpd_overall.py "Jharkhand State"
 spark-submit druid_tpd_overall.py "Madhya Pradesh"
 spark-submit druid_tpd_overall.py "Manipur"
 spark-submit druid_tpd_overall.py "Meghalaya"
 spark-submit druid_tpd_overall.py "Mizoram"
 spark-submit druid_tpd_overall.py "Nagaland"
 spark-submit druid_tpd_overall.py "Odisha"
 spark-submit druid_tpd_overall.py "Pondicherry"
 spark-submit druid_tpd_overall.py "Rajasthan"
 spark-submit druid_tpd_overall.py "Tripura"
 spark-submit druid_tpd_overall.py "सहज | SAHAJ"
 spark-submit druid_tpd_overall.py "Uttarakhand"
 spark-submit druid_tpd_overall.py "NCERT"
 spark-submit druid_tpd_overall.py "Chandigarh"
 spark-submit druid_tpd_overall.py "Chhattisgarh"
 spark-submit druid_tpd_overall.py "Karnataka"
 spark-submit druid_tpd_overall.py "CBSE"
 spark-submit druid_tpd_overall.py "Assam"
 spark-submit druid_tpd_overall.py "Jammu And Kashmir"
 spark-submit druid_tpd_overall.py "Dadra and Nagar Haveli and Daman and Diu"
 spark-submit druid_tpd_overall.py "Ladakh"
 spark-submit druid_tpd_overall.py "MITRA"
 spark-submit druid_tpd_overall.py "Himachal Pradesh"
 spark-submit druid_tpd_overall.py "Goa State"
 spark-submit druid_tpd_overall.py "Tamilnadu"
 spark-submit druid_tpd_overall.py "Telangana State"
 spark-submit druid_tpd_overall.py "Punjab"
