 spark-submit druid_tpd_courses.py "Andaman and Nicobar Islands"
 spark-submit druid_tpd_courses.py "APEKX"
 spark-submit druid_tpd_courses.py "Arunachal Pradesh"
 spark-submit druid_tpd_courses.py "Bihar"
 spark-submit druid_tpd_courses.py "Delhi"
 spark-submit druid_tpd_courses.py "Gujarat"
 spark-submit druid_tpd_courses.py "Haryana"
 spark-submit druid_tpd_courses.py "Jharkhand State"
 spark-submit druid_tpd_courses.py "Madhya Pradesh"
 spark-submit druid_tpd_courses.py "Manipur"
 spark-submit druid_tpd_courses.py "Meghalaya"
 spark-submit druid_tpd_courses.py "Mizoram"
 spark-submit druid_tpd_courses.py "Nagaland"
 spark-submit druid_tpd_courses.py "Odisha"
 spark-submit druid_tpd_courses.py "Pondicherry"
 spark-submit druid_tpd_courses.py "Rajasthan"
 spark-submit druid_tpd_courses.py "Tripura"
 spark-submit druid_tpd_courses.py "सहज | SAHAJ"
 spark-submit druid_tpd_courses.py "Uttarakhand"
 spark-submit druid_tpd_courses.py "NCERT"
 spark-submit druid_tpd_courses.py "Chandigarh"
 spark-submit druid_tpd_courses.py "Chhattisgarh"
 spark-submit druid_tpd_courses.py "Karnataka"
 spark-submit druid_tpd_courses.py "CBSE"
 spark-submit druid_tpd_courses.py "Assam"
 spark-submit druid_tpd_courses.py "Jammu And Kashmir"
 spark-submit druid_tpd_courses.py "Ladakh"
 spark-submit druid_tpd_courses.py "MITRA"
 spark-submit druid_tpd_courses.py "Himachal Pradesh"
 spark-submit druid_tpd_courses.py "Dadra and Nagar Haveli and Daman and Diu"
 spark-submit druid_tpd_courses.py "Goa State"
 spark-submit druid_tpd_courses.py "Tamilnadu"
 spark-submit druid_tpd_courses.py "Telangana State"
 spark-submit druid_tpd_courses.py "Punjab"
